# Generated by Django 4.2.14 on 2024-07-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['ticker', 'date'], name='backend_sto_ticker_71a9ed_idx'),
        ),
    ]
