name: CI/CD for Frontend and Backend with Helm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Build and Push Frontend Docker Image
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stock-frontend:1.1 .
        working-directory: ./frontend

      - name: Push Frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stock-frontend:1.1

      # Build and Push Backend Docker Image
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Build Backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stock-backend:1.1 .
        working-directory: ./backend

      - name: Push Backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stock-backend:1.1

      # Set up Kubernetes and Helm
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure Kubernetes
        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: helm upgrade --install tech-demo /home/sigmoid/TECH-DEMO/helm-chart --set image.backend.repository=${{ secrets.DOCKER_USERNAME }}/stock-backend --set image.backend.tag=1.1 --set image.frontend.repository=${{ secrets.DOCKER_USERNAME }}/stock-frontend --set image.frontend.tag=1.1
